# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Andrew S. Tubbs
    url: /about-me/
    weight: 20
  - name: The Mind after Midnight
    url: /the-mind-after-midnight/
    weight: 30
  - name: Other Projects
    url: /other-projects/
    weight: 40